### ISSUE TITLE
useFetch

### ISSUE THREAD

**Issue by quisido** [uidotdev/usehooks#15]
Mimics the Fetch API, but also supports React 16.6's <Suspense> component for falling back to a different view until the fetch request has resolved.

[CharlesStover/fetch-suspense](https://github.com/CharlesStover/fetch-suspense/)

**Comment by gragland** [comment]
@CharlesStover This is cool. Just trying to understand it better since I haven't actually played around with Suspense yet. It looks like it relies on Suspense and the promise resolving to trigger a re-render, which causes `useFetch` to be called again, at which point it iterates through `fetchCaches` and returns the correct `fetchCache.response`. Is that correct? Does that mean it has to be used within suspense to work properly?

**Comment by quisido** [comment]
That is how it works, but it does not have to be used with Suspense. It throws a Promise so long as the fetch request has not resolved or rejected. Any component may implement `componentDidCatch` to handle the thrown Promise in their own way. The `<Suspense>` component is a a React-internal implementation, so I would recommend it, but it is not a requirement.

You can read about the development process [here](https://medium.com/@Charles_Stover/react-suspense-with-the-fetch-api-a1b7369b0469) or see an implementation of a Suspense-like Component [here](https://gist.githubusercontent.com/CharlesStover/305d16d10094bf0b53bfdf9476b075f1/raw/33d4b89394b060b91575bb63a8f7ceaf628aa624/suspense-promise.js).

**Comment by otakustay** [comment]
A globally cached fetch is not as safe as developers expected, the `createUseFetch` is also not friendly enough since it requires developers to know too many implement details.

I find a better solution to handle the lifespan of a fetch using a context as illustrated here: https://github.com/ecomfe/react-suspense-boundary

**Comment by quisido** [comment]
Not every package matches every user's use case, and that's okay. The current design was in response to community-driven feedback and contributions. Alternatives and abstractions exist for every hook, and this one is no exception. This one does what it does well, especially when using unauthenticated API requests.
