### ISSUE TITLE
Why do many of the hooks require react experimental?

### ISSUE THREAD

**Issue by Seanmclem** [uidotdev/usehooks#231]
Why do many of the hooks require react experimental? That seems odd. For a useKeypress? it's a keypress. why?

**Comment by Xeonian** [comment]
Because they rely on [useEffectEvent](https://react.dev/learn/separating-events-from-effects#declaring-an-effect-event), which is itself only included in the experimental release of React at time of writing. I'm not a frontend dev by trade so I haven't done the reading around _why_ this particular hook is used, but I presume a workaround without it is either error prone or just messy.
