### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gragland** [uidotdev/usehooks#4]
Paginate the front page using https://www.gatsbyjs.org/packages/gatsby-paginate/

**Comment by danedavid** [comment]
I can take this up?

**Comment by danedavid** [comment]
@gragland 
I've added basic pagination using `gatsby-paginate`. Please go through the code in the commit. For reference, I've pushed the built `index.html` onto my `gh-pages` branch, so can be viewed here: https://danedavid.github.io/usehooks ( the links don't work because I've not hosted it ). Please update me with necessary styles changes or any other. Will raise a PR after that.

**Comment by gragland** [comment]
Thanks @danedavid, this looks great! No immediate changes come to mind so feel free to raise a PR and I'll merge.

**Comment by danedavid** [comment]
Raised: https://github.com/gragland/usehooks/pull/33
